### ISSUE TITLE
Need access to Basic PDF headers and Footers.

### ISSUE THREAD

**Issue by humphreyja** [HarvestProfit/harvest-profit-pdf#2]
You should use a basic header with a HP footer or the opposite.  Just needs to be added to the exports.

@jarydkrish I'd create a PR but I do not have access to write to this repo apparently.

**Comment by jarydkrish** [comment]
Huh... you're a member of @HarvestProfit/admin, so you should by default have write access to all repos. I'll check into that.

This is super easy to fix, give me just a sec and I'll create a PR and deploy a new package version to NPM
